### ISSUE TITLE
Hi~ ,Can your DLL run normally in this environment now?

### ISSUE THREAD

**Issue by iuhiyuh** [aduriseti/bwrepml#1]
BWAPI version:BWAPI 4.1.2
StarCraft version:1.16.1
1. I have operated according to your instructions, but there has been a crash.
2. In addition, where is the directory of the generated RGD/RLD/RCD files is normally executed.

**Comment by amal-qokka** [comment]
Having been down this road before - I recommend you checkout the torch integration w/ BWAPI, or alternatively the SC2 API made by google.  Data collection and parsing w/ this tool is not easy or fun and if I had to guess, working w/in the prior 2 frameworks will probably give you access to much more pre parsed data.

As for this project - just to be clear - this is a repo strictly for extracting actions from replays (think there's also an option for live games) and making production decisions off of this data.  There's another repo for actually communicating b/w a ML daemon and bwapi via File IO.  Not that neither repo is up to date or maintained.

As for the RGD,RLD,RCD files I think they are either in a separate repo or stored via googles cloud storage API.
